#!/bin/bash
# A stack is a group of interrelated services that share dependencies, and can be orchestrated and scaled together.
# Add a new service and redeploy
# Open up docker-compose.yml in an editor and replace its contents with the following.

docker-machine ls
eval $(docker-machine env myvm1)
docker stack deploy -c docker-compose.yml getstartedlab
docker service ps getstartedlab_web
docker-machine ls
curl -4 http://192.168.99.100:8080/
# The visualizer is a standalone service that can run in any app that includes it in the stack. It doesn’t depend on anything else. Now let’s create a service that does have a dependency: the Redis service that will provide a visitor counter.
