version: '3'

services:
  # This file defines two services: The db service
  db:
    image: postgres
  # and the web service.
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
